UDP_LIBRARIE=inet_udp
UDP_LIBRARIE_HEADDERS=/home/tim/Robot01/install/libraries

all: main.cpp
	g++ main.cpp -std=gnu++11 -I$(UDP_LIBRARIE_HEADDERS) -L$(UDP_LIBRARIE_HEADDERS) -l$(UDP_LIBRARIE) -o udp_socket_client
